# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Patient Monitor Actions 
on: 
  push:
    branches: [ main, device_module, rest_api ]
  pull_request:
    branches: [ main, device_module, rest_api ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=F401,F403,F504,F506,F821,F823,F841,E303,E302E301,E501,W291,E9,F63,F7,F82 --show-source --statistics --max-line-length=110 
    - name: Test with pytest
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)/device_module"
        python3 api.py &
        pytest
    - name: Run Coverage
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)/device_module"
        python3 api.py &
        coverage run -m pytest
        coverage report
